### PR TITLE
Prerelease1 andpet first PR

### LINKED ISSUE #13: Logging
We need to decide whether we will use `futile.logger`, or simply `message`, `warning`, `stop`, etc.

### LINKED ISSUE #61: Update code after major changes in cerebroApp
The cerebroApp has been rewritten substantially and most of the code for the export does not work anymore. I commented these parts out for now (commit 7b60d91)  but we need to rewrite the function in order to export as much as possible to the cerebroApp.

### LINKED ISSUE #66: in case of few cells error in Seurat::RunPCA
Dear all,

in the case of a project with few cells in a sc-RNA-seq dataset, I am getting the same error as in:

https://github.com/satijalab/seurat/issues/1914

I'm correcting it via editing the npcs argument (default npcs=50), such as follows:

sc = Seurat::RunPCA(sc, features=Seurat::VariableFeatures(object=sc), verbose=FALSE, npcs=14)

Best,

Dimitra

### LINKED ISSUE #71: Prefix for metadata
Let's fix the way we handle metadata column names in case we deal with multiple samples (with equal column names). 

* Writing in HTO script
* Reading in the main script

### LINKED ISSUE #74: Improve output
Let's collect ideas of what else would be useful to add to the output: 

- plots as objects, in addition to pdf and png

### LINKED ISSUE #77: Integrate additional data in sc object
Let us see which additional information we can add to the `sc` object:
- marker genes and pathways split by cluster in misc
- degs and pathways split by comparison
- mito genes list
- cell cycle lists
- any user-provided gene list
- parameters
- sessionInfo
- colours
- high-expressed genes

Then we only have to save the `sc` object and scripts for further analyses just need to load this object.

### LINKED ISSUE #80: Output files for differentially expressed genes
Contrasts: Can we have ONE file with one tab per contrast? (as we have one tab per cluster for marker genes)

Functions: I'd prefer if we only write files if there is something to write, i.e. there are enriched functions and so on... In my current report, there are no enrichments, but a tab called "All" with only the headers.

### LINKED ISSUE #81: add export to h5ad for interactive visualisation with cellxgene
Would be great to convert the final Seurat object to h5ad such that it can be visualized with cellxgene. This could just go next to the exports for Loupe and Cerebro. I would suggest to use sceasy for this (https://github.com/cellgeni/sceasy), this would add a dependency. Code would be something like:

```R
sceasy::convertFormat(sc, from="seurat", to="anndata", assay=DefaultAssay(sc), outFile=paste0(param$path_out,"/anndata.h5ad"))
```

### PR DESCRIPTION
**Pull request by andpet0101**
So, as discussed, this will be the first PR to incorporate changes made in prerelease1_andpet into master. I will then continue using this branch for further development towards release. The content of the PR is:

* Possiblity to use reciprocal pca for integration
* Updated the cell/feature filter tables so that they look better
* Added an script for running scrnaseq_hto.Rmd non-interactively
* Added possiblity to downsample cells for DEG testing for speed
* Added script for applying the per-sample results of the scrnaseq_hto workflow to the aggregated result generated by cellranger. 
* Added lists, colours, marker and degs to the Seurat object as well as some metadata
* Export to anndata for cellxgene
* Added additional output: Counts with metadata as sparse assay, cell metadata and gene annotation as Excel table
 
Closes #71, closes #13, closes #66, closes #77, closes #81, closes #80, closes #74, closes #61.

Many changes are up for discussion. I tried to follow the style guide but the major focus here should be on code and functionality.

Have fun!

### CODE REVIEW

File: R/functions_analysis.R [hunk 1]
```diff
@@ -51,4 +57,192 @@ cc_scoring = function(sc, genes_s, genes_g2m, name=""){
...
+  
+  # Multiply counts by size factors
+  # Use R matrix multiplication for speed: matrix %*% diag(v)
+  # To divide, multiply by the inverse
+  # Finally log1p
+  sc = Seurat::SetAssayData(sc, slot="data", 
+                            assay=assay, 
+                            new.data=log1p(Matrix::t(Matrix::t(counts_assay) * size_factors)))
+  return(sc)
+}
```
Comment (ktrns) [inline R/functions_analysis.R:248]: Wow, that is nice of you, thanks for including this. There is also a scale factor for the usual normalisation function, but if it works like this, very nice.

File: R/functions_analysis.R [hunk 2]
```diff
@@ -51,4 +57,192 @@ cc_scoring = function(sc, genes_s, genes_g2m, name=""){
...
+                                    k.weight=k_weight,
+                                    verbose=verbose)
+
+    rm(integrate_SCT_features, integrate_SCT_anchors)
+  }
+  
+  # Call garbage collector to free memory (hope it helps)
+  gc(verbose=verbose)
+  return(sc)
+}
```
Comment (ktrns) [inline R/functions_analysis.R:212]: What's the motivation to move this from the script to a function, since we are only using it once in the script? Make the main script lighter?

Why does this function need a review? In general, or did you change something in comparison to the main script?

File: R/functions_degs.R [hunk 3]
```diff
@@ -472,6 +472,13 @@ DegsSetupContrastsList = function(sc, contrasts_table, latent_vars=NULL) {
       }
     } 
     
+    # Get number of cells to downsample
```
Comment (ktrns) [inline R/functions_degs.R:475]: What's the idea of downsampling for DEG testing?

File: R/functions_degs.R [hunk 4]
```diff
@@ -641,3 +661,12 @@ EnrichrWriteResults = function(enrichr_results, file) {
...
   return(file)
 }
+
+
+#' Flattens the list of Enrichr results into one data.frame.
+# '
+#' @param enrichr_results: A list with enrichr results.
+#' @return A data.frame with the columns reported by Enrichr as well as the db
+FlattenEnrichr = function(enrichr_results) {
+  return(purrr::invoke(dplyr::bind_rows, purrr::map(names(enrichr_results), function(n) return(data.frame(Database=n, enrichr_results[[n]])))))
```
Comment (ktrns) [inline R/functions_degs.R]: Can you have this over multiple rows, its a bit difficult to read.

File: R/functions_io.R [hunk 5]
```diff
@@ -514,135 +516,82 @@ ParsePlateInformation = function(cell_names, pattern='^(\\S+)_(\\d+)_([A-Z])(\\d
...
+  #
+  #examp$addMostExpressedGenes(group_name="sample", table=tbl)
+  
+  #
+  # Most expressed genes
+  #
+  #examp$addMostExpressedGenes(group_name="sample", table=tbl)
+  saveRDS(cerebro, path)
+  
+  return(path)
```
Comment (ktrns) [inline R/functions_io.R:596]: Thanks for taking care of the Cerebro export.

File: R/functions_util.R [hunk 6]
```diff
@@ -18,8 +28,7 @@ scrnaseq_session_info = function(path_to_git=".") {
   out = matrix(NA, nrow=0, ncol=2)
   colnames(out) = c("Name", "Version")
   
-  repo = tryCatch({system(paste0("git --git-dir ", path_to_git, "/.git log --format='%H' -n 1"), intern=TRUE)},
-    warning = function(war) {return("Unknown")})
+  repo = git_repository_version(path_to_git)
```
Comment (ktrns) [inline R/functions_util.R]: Can you adapt the function names of this new function and the session info function? Thanks

File: R/functions_util.R [hunk 7]
```diff
@@ -262,7 +304,7 @@ Error = function(x, options){
   knitr::asis_output(format_error(x, options))
 }
 
-# Report parameters in a table.
+#' Report parameters in a table.
```
Comment (ktrns) [inline R/functions_util.R:307]: The function names syntax is still "wrong" for a few functions here. You could adapt it now, or we do it later...

File: README.md [hunk 8]
```diff
@@ -395,12 +395,13 @@ These columns are optional:
...
-  * `MAST`:  uses a hurdle model tailored to scRNA-seq data implemented in the the MAST package
-  * `DESeq2`: tests using the DESeq2 package
-  * For more information on the tests, please see the documentation on the `FindMarkers` function of the Seurat R package 
+  * `negbinom`: Tests based on a negative binomial generalized linear model
+  * `poisson`: Tests based on a poisson generalized linear model (only UMI datasets)
+  * `LR`: Tests based on a logistic regression model
+  * `MAST`:  Uses a hurdle model tailored to scRNA-seq data implemented in the the MAST package
+  * `DESeq2`: Tests using the DESeq2 package
+  * For more information on the tests, please see the documentation on the `FindMarkers` function of the Seurat R package
+* `downsample_cells_n`: Downsample each group to at most n cells to speed up tests
```
Comment (ktrns) [inline README.md:404]: Is this something you do for testing?

File: scripts/apply_hto_for_cellranger_aggregate.R [hunk 9]
```diff
@@ -0,0 +1,153 @@
...
+# Which packages are needed
+library(knitr)
+suppressPackageStartupMessages(library("argparse"))
+
+# Prepare parser for arguments
+parser = ArgumentParser(
+  add_help=TRUE,
+  prog=script_name,
+  description="After demultiplexing of individual samples with the with the scrnaseq_hto workflow, this script applies the by-sample results to the merged dataset produced by cellranger aggregate.",
+  epilog="Demultiplexing by sample has to been run first and the results must be in a subdirectory 'demultiplexed'. The script will then read the metadata.tsv.gz files per sample and adjust the cell barcodes suffixes (e.g. '-1' will become '-2' for the second sample) in the cellranger aggregate results accordingly. It will also update the CSV file with the cell identities for import into the Loupe Cell Browser. Important: The script needs to be run in the same directory as cellranger aggregate!")
```
Comment (ktrns) [inline scripts/apply_hto_for_cellranger_aggregate.R]: Can you break down the long lines to multiple lines, so that they are better readable? 

Typo: Demultiplexing by sample has to BE run first ... 

Also, I am not quite sure yet, I understand the purpose. Is it that this script adapts the Cell Ranger aggregate results, such that one can read in the data to Loupe again, recognising the different (sub)samples? What happens, when we have 3 samples, each of which has 3 subsamples separated by HTOs?

File: scripts/run_scrnaseq_hto.R [hunk 10]
```diff
@@ -0,0 +1,185 @@
...
+# Which packages are needed
+library(knitr)
+suppressPackageStartupMessages(library("argparse"))
+
+# Prepare parser for arguments
+parser = ArgumentParser(
+    add_help=TRUE,
+    prog=script_name,
+    description="Demultiplexes a single cell dataset containing samples tagged by hashtags with the scrnaseq_hto workflow.",
+    epilog="Upon successfull completion, the output directory will contain a HTML report, the counts per sample and a CSV file with the cell identities for import into the Loupe Cell Browser.")
```
Comment (ktrns) [inline scripts/run_scrnaseq_hto.R]: Again, I'd prefer multiple lines. 

Typo "AN HTML report..." (you pronounce H here as Eigh, not 100% sure, but I think its about the pronunciation.)

File: scripts/run_scrnaseq_hto.R [hunk 11]
```diff
@@ -0,0 +1,185 @@
...
+}
+
+# Param path_to_git
+if ("path_to_git" %in% names(opt)) {
+    paramsList[["path_to_git"]] = opt[["path_to_git"]]
+}
+
+# Param debugging_mode: 'default_debugging' for RStudio, 'terminal_debugger' for debugging on a terminal without X11, 'print_traceback' for non-interactive sessions
+paramsList[["debugging_mode"]] = 'print_traceback'
+
```
Comment (ktrns) [inline scripts/run_scrnaseq_hto.R:114]: Just a comment: shouldn't the above be part of the HTO script, the way you check parameters for the main script? I just wonder, what we need a wrapper script for.

File: scrnaseq.Rmd [hunk 12]
```diff
@@ -67,7 +67,8 @@ knitr::opts_chunk$set(echo=TRUE,                     # output code
                       dev=c('png', 'pdf'),           # create figures in png and pdf; the first device (png) will be used for HTML output
                       dev.args=list(png=list(type="cairo"),  # png: use cairo - works on cluster, supports anti-aliasing (more smooth)
                                     pdf=list(bg="white")),     # pdf: use cairo - works on cluster, supports anti-aliasing (more smooth)
-                      dpi=96                         # figure resolution
+                      dpi=96,                         # figure resolution
+                      fig.retina=2                   # DISCUSS: http://zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/#the-fig.retina-argument-is-a-resolution-multiplier
```
Comment (ktrns) [inline scrnaseq.Rmd]: Seems fine to me ...

File: scrnaseq.Rmd [hunk 13]
```diff
@@ -93,14 +94,9 @@ param$path_data = data.frame(name=c("pbmc_10x","pbmc_smartseq2"),
...
 
-#param$path_data = data.frame(name="pbmc_10x",
-#                             type="10x",
-#                             path="test_datasets/10x_SmartSeq2_pbmc_GSE132044/counts/10x/",
-#                             stats=NA)
-
 # Downsample data to at most n cells per sample (mainly for tests)
 #   NULL to deactivate
-param$downsample_cells_n = NULL
+param$downsample_cells_n = 100
```
Comment (ktrns) [inline scrnaseq.Rmd]: Change to NULL again

File: scrnaseq.Rmd [hunk 14]
```diff
@@ -277,11 +282,12 @@ switch (param$debugging_mode,
 # Set output hooks
 knitr::knit_hooks$set(message=format_message, warning=format_warning)
 
-# Create output directories
+# Create output directories <==== How about we organise a bit more :-)
```
Comment (ktrns) [inline scrnaseq.Rmd:287]: We can, but for now I think it is fine. I don't mind.

File: scrnaseq.Rmd [hunk 15]
```diff
@@ -300,14 +308,9 @@ error_messages = c(error_messages, check_ensembl(biomart="ensembl",
...
-```
 
-```{r initial_checks_failed, eval=length(error_messages) > 0, include=length(error_messages) > 0}
-# Now format collected error messages as error boxes, print and exit
-# Note: asis_output prints a content as is; knit_exist toggles knitr to exit after the current chunk
-error_message_blocks = purrr::map(error_messages, format_error) %>% paste(collapse="")
-knitr::knit_exit()
-knitr::asis_output(error_message_blocks)
+# Stop here if there are errors
+if (length(error_messages)) stop(paste(c("",paste("*", error_messages)), collapse="\n"))
```
Comment (ktrns) [inline scrnaseq.Rmd]: spaces

File: scrnaseq.Rmd [hunk 16]
```diff
@@ -503,10 +506,12 @@ sc = purrr::map(list_indices(sc), function(i){
   Seurat::RenameCells(sc[[i]], new.names=paste(cell_names, i, sep="-"))
 })
 
-# Set up colors for samples
-sample_names = purrr::flatten_chr(purrr::map(sc, function(s){ unique(as.character(s[[]][["orig.ident"]])) }))
+# Set up colors for samples and add to the sc objects
+sample_names = purrr::flatten_chr(purrr::map(sc, function(s) { return(unique(as.character(s[[]][["orig.ident"]]))) }))
```
Comment (ktrns) [inline scrnaseq.Rmd]: Multiple lines, those long lines with so many `([` are difficult to read ...

File: scrnaseq.Rmd [hunk 17]
```diff
@@ -503,10 +506,12 @@ sc = purrr::map(list_indices(sc), function(i){
...
 param$col_samples = GenerateColours(num_colours=length(sample_names), palette=param$col_palette_samples)
 names(param$col_samples) = sample_names
+sc = purrr::map(list_names(sc), function(n) return(ScAddLists(sc[[n]], lists=list(samples=param$col_samples[n]), lists_slot="colour_lists")))
```
Comment (ktrns) [inline scrnaseq.Rmd]: Multiple lines

File: scrnaseq.Rmd [hunk 18]
```diff
@@ -563,14 +568,16 @@ param$feature_filter = purrr::map(list_names(sc), function(s) {
 # Calculate percentage of counts in mitochondrial genes for each Seurat object
 sc = purrr::map(sc, Seurat::PercentageFeatureSet, pattern=param$mt, col.name="percent_mt", assay="RNA")
 
+## percent_ribo?
```
Comment (ktrns) [inline scrnaseq.Rmd]: Sure

File: scrnaseq.Rmd [hunk 19]
```diff
@@ -689,21 +696,31 @@ ggplot(genes_highestExpr_counts, aes(x=name, y=value, col=gene, group=gene)) +
...
+  knitr::kable(align="l", caption="Categorial filters applied to cells", col.names=c("Values")) %>% 
+  kableExtra::kable_styling(bootstrap_options=c("striped", "hover"))
+}
   
-knitr::kable(feature_filter_tbl, align="l", caption="Filters applied to genes") %>% 
-  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))
+# gene filters
+feature_filter_lst = param$feature_filter %>% unlist(recursive=FALSE)
+if (length(feature_filter_lst) > 0) {
+  feature_filter_lst = param$feature_filter %>% unlist(recursive=FALSE)
```
Comment (ktrns) [inline scrnaseq.Rmd]: Duplicated line

File: scrnaseq.Rmd [hunk 20]
```diff
@@ -806,16 +823,15 @@ Note that removing all signal associated to cell cycle can negatively impact dow
...
+sc = purrr::map(sc, Seurat::NormalizeData, normalization.method="LogNormalize", scale.factor=10000, verbose=FALSE)
 ```
 
 ```{r part2_cc_scores}
 # Determine cell cycle effect per sample 
 sc = purrr::map(list_names(sc), function(n) {
-  sc[[n]] = cc_scoring(sc=sc[[n]], genes_s=genes_s[,2], genes_g2m=genes_g2m[,2], name=n)
-  if (all(is.na(sc[[n]][["S.Score"]])) & all(is.na(sc[[n]][["G2M.Score"]]))) param$cc_remove=FALSE
+  sc[[n]] = CCScoring(sc=sc[[n]], genes_s=genes_s[,2], genes_g2m=genes_g2m[,2], name=n)
+  if (any(is.na(sc[[n]][["S.Score"]])) | any(is.na(sc[[n]][["G2M.Score"]]))) param$cc_remove=FALSE
```
Comment (ktrns) [inline scrnaseq.Rmd:848]: Can you briefly explain, why we need `any` instead of `all`?

File: scrnaseq.Rmd [hunk 21]
```diff
@@ -861,12 +877,14 @@ if (param$norm == "RNA") {
...
   #   See: https://github.com/ChristophH/sctransform/issues/27
+  # Note: The performance of SCTransform can be improved by using 'glmGamPoi' instead of 'poisson' as method for initial parameter estimation.
   sc = purrr::map(list_names(sc), function(n) { 
     SCTransform(sc[[n]], 
                 vars.to.regress=param$vars_to_regress, 
                 min_cells=param$feature_filter[[n]][["min_cells"]], 
                 verbose=FALSE, 
-                return.only.var.genes=!(param$integrate_samples[["method"]]=="single")) 
+                return.only.var.genes=!(param$integrate_samples[["method"]]=="single"),
+                method=ifelse(packages_installed("glmGamPoi"), "glmGamPoi", "poisson"))
```
Comment (ktrns) [inline scrnaseq.Rmd:901]: What is this about? Why not install the package if it is not installed?

File: scrnaseq.Rmd [hunk 22]
```diff
@@ -902,16 +920,17 @@ p
...
 ```
 
 ```{r multi_dataset_integration_preparation, eval=(param$integrate_samples[["method"]]!="single"), include=(param$integrate_samples[["method"]]!="single"), results="asis"}
 if (param$integrate_samples[["method"]]!="single") {
   
-  # When merging, feature meta-data is removed by Seurat entirely; save separately for each assay and add again afterwards
-  assay_names = unique(purrr::flatten_chr(purrr::map(list_names(sc), function(n) { Seurat::Assays(sc[[n]]) } )))
-  
+  # When merging, feature meta-data is removed by Seurat entirely; save separately for each assay except for SCT and add again afterwards
+  # Note: not sure whether this is still needed - discuss
```
Comment (ktrns) [inline scrnaseq.Rmd:945]: Why is it not needed for `SCT`?

File: scrnaseq.Rmd (hunk 20 above)
Comment (ktrns) [reply scrnaseq.Rmd:848]: Further below, after re-scoring, you use `all`.

File: scrnaseq.Rmd [hunk 23]
```diff
@@ -1192,64 +1172,66 @@ We use Principal Component Analysis (PCA) to summarise a dataset, overcoming noi
 To decide how many PCs to include in downstream analyses, we visualise the cells and genes that define the PCA.
 ```{r pca}
 # Run PCA for default normalisation
-sc = Seurat::RunPCA(sc, features=Seurat::VariableFeatures(object=sc), verbose=FALSE)
+sc = Seurat::RunPCA(sc, features=Seurat::VariableFeatures(object=sc), verbose=FALSE, npcs=min(50, ncol(sc)))
```
Comment (ktrns) [inline scrnaseq.Rmd:1189]: `ncol(sc)` is the number of cells?

File: scrnaseq.Rmd [hunk 24]
```diff
@@ -1192,64 +1172,66 @@ We use Principal Component Analysis (PCA) to summarise a dataset, overcoming noi
...
+Seurat's clustering method first constructs a graph structure, where nodes are cells and edges are drawn between cells with similar gene expression patterns. Technically speaking, Seurat first constructs a K-nearest neighbor (KNN) graph based on Euclidean distance in PCA space, and refines edge weights between cells based on the shared overlap in their local neighborhoods (Jaccard similarity). To partition the graph into highly interconnected parts, cells are iteratively grouped together using the Leiden algorithm `r Cite("10.1038/s41598-019-41695-z", "citep")`. 
 ```{r clustering}
-# Note: I changed the seed in ./lib/python3.6/site-packages/leidenalg/functions.py to 11 for reproducibility
-# The number of clusters can be optimized by tuning 'resolution' -> based on feedback from the client whether or not clusters make sense
+# Construct phylogenetic tree relating the 'average' cell from each sample
+sc = Seurat::BuildClusterTree(sc, features=rownames(sc), verbose=FALSE)
```
Comment (ktrns) [inline scrnaseq.Rmd:1229]: What do we need the cluster tree for, actually?

File: scrnaseq.Rmd [hunk 25]
```diff
@@ -1192,64 +1172,66 @@ We use Principal Component Analysis (PCA) to summarise a dataset, overcoming noi
...
-# Taken from documentation:
-#   Method for running leiden (defaults to matrix which is fast for small datasets). Enable method = "igraph" to avoid casting large data to a dense matrix.
-# Note Katrin: 
-#   This is implemented as default recently and will be updated with a new Seurat release
-#   https://github.com/satijalab/seurat/pull/3233
 sc = Seurat::FindClusters(sc, resolution=param$cluster_resolution, algorithm=4, verbose=FALSE, method="igraph")
 
 # Construct phylogenetic tree relating the 'average' cell from each cluster
-sc = BuildClusterTree(sc, dims=1:param$pc_n, verbose=FALSE)
+sc = Seurat::BuildClusterTree(sc, dims=1:param$pc_n, verbose=FALSE)
```
Comment (ktrns) [inline scrnaseq.Rmd:1240]: So you added a `BuildClusterTree` call above based on all features, and this one is for the PCs. Again, why do we need this?

File: scrnaseq.Rmd [hunk 26]
```diff
@@ -1713,14 +1710,14 @@ if (markers_found) {
 ```{r markers_plot_violin_raw, eval=markers_found, fig.height=fig_height_markers}
 if (markers_found) {
   # Violin plot of raw gene expression counts
-  p_list = Seurat::VlnPlot(sc, features=markers_examples, assay="RNA", slot="counts", combine=FALSE, pt.size=0.2)
+  p_list = Seurat::VlnPlot(sc, features=markers_examples, assay="RNA", slot="counts", combine=FALSE, pt.size=0)
```
Comment (ktrns) [inline scrnaseq.Rmd]: I like to see the dots, and prefer if we leave them in small-ish like before.

File: scrnaseq.Rmd [hunk 27]
```diff
@@ -1729,14 +1726,14 @@ if (markers_found) {
 ```{r markers_plot_violin_norm, eval=markers_found, fig.height=fig_height_markers}
 if (markers_found) {
   # Violin plot of normalised gene expression data
-  p_list = Seurat::VlnPlot(sc, features=markers_examples, combine=FALSE, pt.size=0.2)
+  p_list = Seurat::VlnPlot(sc, features=markers_examples, combine=FALSE, pt.size=0)
```
Comment (ktrns) [inline scrnaseq.Rmd]: Same here

File: scrnaseq.Rmd [hunk 28]
```diff
@@ -1933,7 +1930,10 @@ markers_enriched=list()
 
 ```{r markers_functional_enrichment, results="hide", eval=markers_found}
 if (markers_found) {
+  # Upregulated markers
+  
   # Convert Seurat names of upregulated marker per cluster to Entrez; use named lists for translation
+  # Is that still neccessary?
```
Comment (ktrns) [inline scrnaseq.Rmd:1950]: Yeah, I don't know by heart. I will take some time later to check it out.

File: scrnaseq.Rmd [hunk 29]
```diff
@@ -1942,14 +1942,23 @@ if (markers_found) {
   
   # Tests done by Enrichr
   marker_genesets_up_enriched = purrr::map(marker_genesets_up, EnrichrTest, databases=param$enrichr_dbs, padj=param$enrichr_padj)
-  
+  marker_genesets_up_enriched = purrr::map(list_names(marker_genesets_up_enriched), function(n) {
```
Comment (ktrns) [inline scrnaseq.Rmd:1959]: Why did you need to change the above line? It was so nice and short ... was anything wrong?

File: scrnaseq.Rmd [hunk 30]
```diff
@@ -1974,44 +1999,17 @@ The following table contains the top enriched terms per cluster.
...
-    }) %>% head()
-  })
-  
-  # Join
-  marker_genesets_top_enriched = purrr::map(values_to_names(names(marker_genesets_down_top_enriched)), function(n) {
-    return(rbind(marker_genesets_up_top_enriched[[n]], marker_genesets_down_top_enriched[[n]]) %>% 
-      dplyr::arrange(-Odds.Ratio))
-    })
+  # Get top ten up and down over all databases per cluster
+  marker_genesets_top_enriched = marker_genesets_enriched %>% dplyr::group_by(Cluster, Direction) %>%
```
Comment (ktrns) [inline scrnaseq.Rmd:2017]: Ok, so is the difference that we don't have lists any more and rather a bigger table?

File: scrnaseq.Rmd [hunk 31]
```diff
@@ -2290,91 +2369,70 @@ for (i in names(genesets_to_export)) {
...
-                      column_cluster="seurat_clusters", 
-                      column_ccphase="Phase", 
-                      gene_lists=gene_lists_for_cerebro, 
-                      marker_genes=markers_filt$all, 
-                      enriched_pathways=enriched)
+                      assay=DefaultAssay(sc),
+                      delayed_array=FALSE)
 ```
 
-## Output files
```
Comment (ktrns) [inline scrnaseq.Rmd:2331]: Good idea to move it up.

File: scrnaseq.Rmd [hunk 32]
```diff
@@ -2290,91 +2369,70 @@ for (i in names(genesets_to_export)) {
...
 knitr::kable(out, align="l") %>% 
-  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))
+  kableExtra::kable_styling(bootstrap_options=c("striped", "hover"))
 ```
 
+
 # References
 ```{r bib, message=FALSE}
+# If the DOI publication servers cannot be reached, there will be no citations, knitcitations will not write a references.bib file and pandoc will stop. This makes sure that there is always at least one citation.
+invisible(knitcitations::citep(citation("knitr")))
```
Comment (ktrns) [inline scrnaseq.Rmd]: I added this very much to the top, so its there before the early exit can happen in case of an error.

Comment (ktrns) [reply scrnaseq.Rmd]: But I see that you removed the `knit` exit, and added a `stop`, so never mind.

**Review by ktrns — COMMENTED** [review]
Thanks for all the changes, and especially the new normalisation option, so I don't have to implement it myself. 

Few comments, as always. 

Best & thanks,
Katrin

File: R/functions_analysis.R (hunk 1 above)
Comment (andpet0101) [reply R/functions_analysis.R:248]: It should work. I tested it with max_fraction = 1 (do not exclude genes) and the sum of the un-logged data adds up to 10000. The size factors are just a combination of the sums and the scale factor.

File: R/functions_analysis.R (hunk 2 above)
Comment (andpet0101) [reply R/functions_analysis.R:212]: Before this PR, it was already in a function which was however was defined in the main script. I moved it for a clearer and better code.

File: R/functions_degs.R (hunk 3 above)
Comment (andpet0101) [reply R/functions_degs.R:475]: Especially with large datasets it makes a difference in speed whether you test 300 cells vs 300 cells or 3000 cells vs 3000 cells. This is mentioned here: https://satijalab.org/seurat/articles/de_vignette.html .

File: R/functions_degs.R (hunk 4 above)
Comment (andpet0101) [reply R/functions_degs.R]: changed it

File: R/functions_util.R (hunk 6 above)
Comment (andpet0101) [reply R/functions_util.R]: should be now done, also for scrnaseq_params_info

File: README.md (hunk 8 above)
Comment (andpet0101) [reply README.md:404]: It can be used for testing but it should help to speed up DEG tests

File: scripts/apply_hto_for_cellranger_aggregate.R (hunk 9 above)
Comment (andpet0101) [reply scripts/apply_hto_for_cellranger_aggregate.R]: Typo is fixed. I will try to wrap long lines but in this case it is a text which should stay together. For code I can try.

Yes, the purpose of the script is to apply the hashtag demultiplexing results of the individual 10x datasets to the results of cellranger aggregate (which aggregates the 10x datasets). This is useful for people who rather work on the primary cellranger results using Loupe. The script provides counts split by hashtag oligo as well as a csv file that can be imported into Loupe and allows to separate cells by hashtag oligos.

When the same hashtag oligo may be used in multiple dataset, it will be named 'dataset.hashtag_oligo_name'.

File: scripts/run_scrnaseq_hto.R (hunk 10 above)
Comment (andpet0101) [reply scripts/run_scrnaseq_hto.R]: Changed. In this particular example, I will leave the line as is. Alternative might be a heredoc string:

```
epilog="Upon successfull completion, the output directory will contain a HTML report, 
the counts per sample and a CSV file with the cell identities for import into the Loupe Cell Browser."
```

But I am not sure whether I prefer this.

File: scripts/run_scrnaseq_hto.R (hunk 11 above)
Comment (andpet0101) [reply scripts/run_scrnaseq_hto.R:114]: Well in this case it may indeed be a bit redundant since if not set it will be set automatically in the rmd script.

The wrapper script is neccessary to safely and nicely call the rmd script.

File: scrnaseq.Rmd (hunk 12 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: Here is the same report compiled with fig.retina=1 (96dpi) and fig.retina=2 (182dpi): https://cloudstore.zih.tu-dresden.de/index.php/s/2FzxDijSQsnZ8r9

The report with fig.retina=2 is twice as large. But, if you zoom in on fig.retina=1 pictures you will see some differences. I would say that I do not need high resolution since there is always a pdf available (which is independent of resolution).

File: scrnaseq.Rmd (hunk 13 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: Will do but if I forget change it.

File: scrnaseq.Rmd (hunk 15 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: done

File: scrnaseq.Rmd (hunk 16 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: done

File: scrnaseq.Rmd (hunk 17 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: done

File: scrnaseq.Rmd (hunk 18 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: Okay I have changed the code as follows:

```
# Calculate percentage of counts in mitochondrial genes for each Seurat object
sc = purrr::map(sc, function(s) {
  mt_features = grep(pattern=param$mt, rownames(sc), value=TRUE)
  return(Seurat::PercentageFeatureSet(s, features=mt_features, col.name="percent_mt", assay="RNA"))
})

# Calculate percentage of counts in ribosomal genes for each Seurat object
sc = purrr::map(sc, function(s) {
  ribo_features = grep(pattern="^RP[SL]", rownames(sc), value=TRUE, ignore.case=TRUE)
  return(Seurat::PercentageFeatureSet(s, features=ribo_features, col.name="percent_ribo", assay="RNA"))
})
```

Ribo genes are based on what I found here: https://nbisweden.github.io/excelerate-scRNAseq/session-qc/Quality_control.html

File: scrnaseq.Rmd (hunk 19 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: deleted the first line

File: scrnaseq.Rmd (hunk 20 above)
Comment (andpet0101) [reply scrnaseq.Rmd:848]: I think that we can only remove the cell cycle information if we have information for all cells. If any score is NA, then it should not be possible anymore. Of course I have never seen such a case.

I will adjust it below as well.

File: scrnaseq.Rmd (hunk 21 above)
Comment (andpet0101) [reply scrnaseq.Rmd:901]: The package is only available for R 4.0.0. Therefore I would not like to enforce this for now.

File: scrnaseq.Rmd (hunk 22 above)
Comment (andpet0101) [reply scrnaseq.Rmd:945]: The metadata for SCT features is less meaningful - it is basically only the variable genes info. But see for yourself please

File: scrnaseq.Rmd (hunk 23 above)
Comment (andpet0101) [reply scrnaseq.Rmd:1189]: yes, and nrow is the number of features in the active assay

File: scrnaseq.Rmd (hunk 24 above)
Comment (andpet0101) [reply scrnaseq.Rmd:1229]: Its a minor feature but it shows you the relationship between the samples, i.e. which are transcriptionally closest.

File: scrnaseq.Rmd (hunk 25 above)
Comment (andpet0101) [reply scrnaseq.Rmd:1240]: The one above is defined based on expression and relates the samples. This one relates the clusters and is based on PCs (== denoised expression).

Leave them for now. They can be visualised in cerebro. For the clusters, it may be nice to see which clusters are close and which not.

File: scrnaseq.Rmd (hunk 26 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: ok

Comment (andpet0101) [reply scrnaseq.Rmd]: though you do not get much information from the dots and they potentially obscur the violin

File: scrnaseq.Rmd (hunk 27 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: changed

File: scrnaseq.Rmd (hunk 29 above)
Comment (andpet0101) [reply scrnaseq.Rmd:1959]: My intention was to add Database and Direction as columns. By doing this, the tables can easily be flattened into one big table. Thus we do not need to store two lists of lists of tables but only one table.

Also here the code is maybe  a bit longer but in the next chunk it is shorter and clearer.

Finally, I can attach one big table to the Seurat object.

File: scrnaseq.Rmd (hunk 30 above)
Comment (andpet0101) [reply scrnaseq.Rmd:2017]: yes

File: scrnaseq.Rmd (hunk 31 above)
Comment (andpet0101) [reply scrnaseq.Rmd:2331]: Yes though we need to document here

File: scrnaseq.Rmd (hunk 32 above)
Comment (andpet0101) [reply scrnaseq.Rmd]: no, good idea, it is always better that there is at least one entry - it is annoying if at the end pandoc fails

**Comment by andpet0101** [comment]
Okay changes are committed.

File: scripts/apply_hto_for_cellranger_aggregate.R (hunk 9 above)
Comment (ktrns) [reply scripts/apply_hto_for_cellranger_aggregate.R]: Very nice, thanks. 

With regard to the text, I still suggest to break it to multiple lines. Even on the screen, reading a message is nicer with the common 80 characters or so. Leave it if you have a strong opinion about it, just saying I'd prefer multiple lines.

File: scripts/run_scrnaseq_hto.R (hunk 11 above)
Comment (ktrns) [reply scripts/run_scrnaseq_hto.R:114]: Yes I get it. But in the case of the main script, you do all the checks within the Rmd. It's fine, just a bit inconsistent.

File: scrnaseq.Rmd (hunk 12 above)
Comment (ktrns) [reply scrnaseq.Rmd]: Mmmh, what is the actual size of the HTMLs? I prefer `fig.retina=2` over `fig.retina=1`.

File: scrnaseq.Rmd (hunk 13 above)
Comment (ktrns) [reply scrnaseq.Rmd]: Yes, we should make sure that at the end, it is back to NULL. Never mind for the next month while we are developing...

File: scrnaseq.Rmd (hunk 24 above)
Comment (ktrns) [reply scrnaseq.Rmd:1229]: Are we using this any where in the script?

File: scrnaseq.Rmd (hunk 26 above)
Comment (ktrns) [reply scrnaseq.Rmd]: Still, pls leave them for now.
