### PR TITLE
Known features and issue fixes 

### LINKED ISSUE #26: Small fixes
Feedback from Andreas: 
- Introduce HTO name tags
- Introduce the term meta data
- Replace "Identity" y-axis label with "Cluster"
- Introduce what different plots are showing, particularly a dot plot 
- Look up adjusted p-value for DEGs: rounding issue? why is it all 0?

### LINKED ISSUE #30: DEG output table markers.xlsx lacks annotation
It looks as if `markers.xlsx` lacks the annotation. Headers are there, but cells are not filled.

### PR DESCRIPTION
**Pull request by ktrns**
- Fixed #26 
- Fixed #30 
- Improved documentation
- Fixed plotting of known marker genes

### CODE REVIEW

File: R/functions_util.R [hunk 1]
```diff
@@ -11,12 +11,12 @@ first_n_elements_to_string = function(x, n=5, sep=",") {
...
 
 # Report session info in a table
-scrnaseq_session_info = function() {
+scrnaseq_session_info = function(path_to_git) {
   
   out=matrix(NA, nrow=0, ncol=2)
   colnames(out) = c("Name", "Version")
   
-  repo = system("git log --format='%H' -n 1", intern=TRUE)
+  repo = system(paste0("git --git-dir ", path_to_git, "/.git log --format='%H' -n 1"), intern=TRUE)
```
Comment (andpet0101) [inline R/functions_util.R]: What if git is not installed? Can we have a fallback solution?

Comment (ktrns) [reply R/functions_util.R]: Mmh, yes sounds good. Idea how? Date of the file scrnaseq.Rmd?

Comment (ktrns) [reply R/functions_util.R]: Done :-)
